
name: CI

# Controls when the action will run. Triggers the workflow on push request
# events but only for the master branch
on:
  #when there is a push to the master
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under github workspace
    - name: Git checkout
      uses: actions/checkout@v2

    #installs a version of python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    #credentials to connect to AWS
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        profile_name: default
        project_name: CICD
        runtime: python3.8
        s3_bucket: localopenweatherdata

    # Runs a set of commands using the runners shell; This is for first lambda function
    - name: Run a multi-line script for queryopenweatherapi
      run: |
         #install PIP
         python -m pip install --upgrade pip
         cd ./queryopenweatherapi/
         ls -a
         #install all dependencies as defined by requirements.txt in the current directory
         pip3 install -r requirements.txt -t .
         #zip files into current directory
         zip -r ./../queryopenweatherapi.zip .
         cd ..

         #ensuring current working directory is accessible by the function--this might not be doing anything
         export PATH=$PATH:$(pwd)

    #Deploy main.py to AWS
    - name: AWS Lambda Deploy for queryopenweatherapi
      uses: appleboy/lambda-action@v0.0.4
      with:
            #name of my AWS Lambda Function
            function_name: queryopenweatherapi
            #contains all the files in my github repository
            zip_file: queryopenweatherapi.zip
    ######################################################
    # Runs a set of commands using the runners shell; This is for second lambda function
    - name: Run a multi-line script for dataextractor
      run: |
         #install PIP
         python -m pip install --upgrade pip
         cd ./dataextractor/
         ls -a
         #install all dependencies as defined by requirements.txt in the current directory
         pip3 install -r requirements.txt -t .
         #zip files into current directory
         zip -r ./../dataextractor.zip .
         cd ..

         #ensuring current working directory is accessible by the function--this might not be doing anything
         export PATH=$PATH:$(pwd)

    #Deploy main.py to AWS
    - name: AWS Lambda Deploy for dataextractor
      uses: appleboy/lambda-action@v0.0.4
      with:
            #name of my AWS Lambda Function
            function_name: dataextractor
            #contains all the files in my github repository
            zip_file: dataextractor.zip

    ########################################################
    # Runs a set of commands using the runners shell; This is for first lambda function
    - name: Run a multi-line script for querysimplifiedopenweatherdata
      run: |
         #install PIP
         python -m pip install --upgrade pip
         cd ./querysimplifiedopenweatherdata/
         ls -a
         #install all dependencies as defined by requirements.txt in the current directory
         pip3 install -r requirements.txt -t .
         #zip files into current directory
         zip -r ./../querysimplifiedopenweatherdata.zip .
         cd ..

         #ensuring current working directory is accessible by the function--this might not be doing anything
         export PATH=$PATH:$(pwd)

    #Deploy main.py to AWS
    - name: AWS Lambda Deploy for querysimplifiedopenweatherdata
      uses: appleboy/lambda-action@v0.0.4
      with:
            #name of my AWS Lambda Function
            function_name: querysimplifiedopenweatherdata
            #contains all the files in my github repository
            zip_file: querysimplifiedopenweatherdata.zip

    - name: Display directory structure
      run: |
        ls -a
